linters-settings:
  lll:
    line-length: 130
  cyclop:
    max-complexity: 21
linters:
  enable-all: true
  disable:
    - exportloopref
    - tagalign
    - bodyclose
    - exhaustruct
    - varnamelen
