version: "2"
linters:
  default: all
  disable:
    - err113
    - exhaustruct
    - depguard
    - funcorder
    - gochecknoglobals
    - nilnil
    - nlreturn
    - noinlineerr
    - varnamelen
    - wrapcheck
    - wsl
    - wsl_v5
  settings:
    cyclop:
      max-complexity: 21
    lll:
      line-length: 150
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
